/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PagamentoRouteImport } from './routes/pagamento'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'

const PagamentoRoute = PagamentoRouteImport.update({
  id: '/pagamento',
  path: '/pagamento',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/pagamento': typeof PagamentoRoute
  '/produto/$slug': typeof ProdutoSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/pagamento': typeof PagamentoRoute
  '/produto/$slug': typeof ProdutoSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/pagamento': typeof PagamentoRoute
  '/produto/$slug': typeof ProdutoSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/checkout' | '/pagamento' | '/produto/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/checkout' | '/pagamento' | '/produto/$slug'
  id: '__root__' | '/' | '/checkout' | '/pagamento' | '/produto/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  PagamentoRoute: typeof PagamentoRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pagamento': {
      id: '/pagamento'
      path: '/pagamento'
      fullPath: '/pagamento'
      preLoaderRoute: typeof PagamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  PagamentoRoute: PagamentoRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
