// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    console.warn("[Supabase] SUPABASE_URL or SUPABASE_PUBLISHABLE_KEY is missing. Using null client.");
    return null;
  }


  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as any, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    
    // Fallback if client creation failed (missing env vars)
    if (!_supabase) {
      if (prop === 'auth') {
        return {
          getSession: async () => ({ data: { session: null }, error: null }),
          onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => {} } }, error: null }),
          signInWithPassword: async () => ({ data: { user: null, session: null }, error: new Error("Supabase not configured") }),
          signUp: async () => ({ data: { user: null, session: null }, error: new Error("Supabase not configured") }),
          signOut: async () => ({ error: null }),
        };
      }
      return () => ({ 
        error: new Error("Supabase not configured"), 
        data: null,
        select: () => ({ 
          eq: () => ({ 
            single: () => Promise.resolve({ data: null, error: new Error("Supabase not configured") }),
            maybeSingle: () => Promise.resolve({ data: null, error: new Error("Supabase not configured") })
          }) 
        }),
        insert: () => ({ select: () => ({ single: () => Promise.resolve({ data: null, error: new Error("Supabase not configured") }) }) }),
        update: () => ({ eq: () => Promise.resolve({ data: null, error: new Error("Supabase not configured") }) }),
        delete: () => ({ eq: () => Promise.resolve({ data: null, error: new Error("Supabase not configured") }) }),
      });
    }
    
    return Reflect.get(_supabase, prop, receiver);
  },
});


